package utils;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Utility class for writing generated test data
 * to generated-test-data.properties.
 */
public final class TestDataWriter {

    // =========================================================
    // CONSTANTS
    // =========================================================

    private static final String FILE_PATH =
            "src/test/resources/generated-test-data.properties";

    private static final DateTimeFormatter DATE_TIME_FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    // =========================================================
    // CONSTRUCTOR
    // =========================================================

    private TestDataWriter() {
        // Prevent instantiation
    }

    // =========================================================
    // PUBLIC METHODS
    // =========================================================

    public static void save(
            String primaryUsername,
            String primaryPassword,
            String secondaryUsername,
            String secondaryPassword,
            String primaryCustomerId,
            String primarySourceAccountId,
            String primaryDestinationAccountId
    ) {

        try (BufferedWriter writer =
                     new BufferedWriter(new FileWriter(FILE_PATH))) {

            String generatedAt =
                    LocalDateTime.now().format(DATE_TIME_FORMATTER);

            writer.write("# ==========================================================");
            writer.newLine();
            writer.write("# Generated Test Data");
            writer.newLine();
            writer.write("#");
            writer.newLine();
            writer.write("# Environment  : ParaBank Demo");
            writer.newLine();
            writer.write("# Generated By : UserSetupTest");
            writer.newLine();
            writer.write("# Generated At : " + generatedAt);
            writer.newLine();
            writer.write("#");
            writer.newLine();
            writer.write("# NOTE:");
            writer.newLine();
            writer.write("# This file is generated automatically at runtime.");
            writer.newLine();
            writer.write("# Do not edit manually.");
            writer.newLine();
            writer.write("# =========================================================");
            writer.newLine();
            writer.write("# PRIMARY CUSTOMER");
            writer.newLine();
            writer.write("# =========================================================");
            writer.newLine();

            writer.write("primaryUsername=" + primaryUsername);
            writer.newLine();

            writer.write("primaryPassword=" + primaryPassword);
            writer.newLine();

            writer.write("primaryCustomerId=" + primaryCustomerId);
            writer.newLine();

            writer.write("primarySourceAccountId=" + primarySourceAccountId);
            writer.newLine();

            writer.write("primaryDestinationAccountId=" + primaryDestinationAccountId);
            writer.newLine();
            writer.newLine();

            writer.write("# =========================================================");
            writer.newLine();
            writer.write("# SECONDARY CUSTOMER");
            writer.newLine();
            writer.write("# =========================================================");
            writer.newLine();

            writer.write("secondaryUsername=" + secondaryUsername);
            writer.newLine();

            writer.write("secondaryPassword=" + secondaryPassword);
            writer.newLine();

        } catch (IOException e) {
            throw new RuntimeException(
                    "Failed to save generated test data",
                    e
            );
        }
    }
}